### PR TITLE
Node inspector

### PR DESCRIPTION
**Pull request by alelievr**
Added the possibility for certain nodes to have an inspector representation:
InspectorNode

Code of the code:

```CSharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GraphProcessor;
using System.Linq;

[System.Serializable, NodeMenuItem("Custom/InspectorNode")]
public class InspectorNode : BaseNode
{
	[Input(name = "In")]
    public float                input;

	[Output(name = "Out")]
	public float				output;

	[ShowInInspector]
	public bool additionalSettings;
	[ShowInInspector]
	public string additionalParam;

	public override string		name => "InspectorNode";

	protected override void Process()
	{
	    output = input * 42;
	}
}
```

### CODE REVIEW

**Comment by alelievr** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           

Complexity increasing per file
==============================
- Assets/com.alelievr.NodeGraphProcessor/Editor/Views/ToolbarView.cs  4
- Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs  2
- Assets/com.alelievr.NodeGraphProcessor/Editor/NodeInspectorObject.cs  3
- Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/alelievr/NodeGraphProcessor/pullRequest?prid=5842549&bid=19130040)

**Comment by zeon-ktc** [comment]
Hello, how to add list (or array) data show on this inspector window?
I see this array can add on the node's window(https://github.com/alelievr/NodeGraphProcessor/issues/62)
but i also want add that on the unity's inspector window, but i can't find a way to show on it.
thanks.

**Comment by zeon-ktc** [comment]
@alelievr hello, sorry for forget to @ you yesterday, please reply me if you see this.
thanks a lot.

**Comment by alelievr** [comment]
Hey!

The first thing to do is to make sure you enable the inspector for the node with this property: [BaseNode.needsInspector](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Elements/BaseNode.cs#L103)

Then, to show the content of the node in the inspector that has a custom node editor (it's the case in the example I give in #62) you need to override 
```CSharp
	public override void Enable(bool fromInspector)
```
instead of
```CSharp
	public override void Enable()
```
the Enable function will be called twice: one for the inspector with the bool set to true and one for the node with the bool set to false.

**Comment by zeon-ktc** [comment]
Thank you!

**Pull request merged**
