### PR TITLE
Use [SerializeReference] instead of JSON serialization for nodes a parameters

### LINKED ISSUE #67: Recursive Serialization is not supported. You can't dereference a PPtr while loading (occasional crash)
First off, fantastic project. I'm thoroughly impressed with where is going.

Unity version is `2019.3.15f1`

Either Unity crashes while loading or, if it does load, I have this error in the console.

```
Recursive Serialization is not supported. You can't dereference a PPtr while loading. (Constructors of C# classes may not load objects either. See stacktrace.)
UnityEngine.JsonUtility:FromJsonOverwrite(String, Object)
GraphProcessor.SerializableObject:OnAfterDeserialize() (at Assets/com.alelievr.NodeGraphProcessor/Runtime/Utils/SerrializableObject.cs:54)
```

I checked the `Editor.log` and found this that looked relevant:
```
Assertion failed on expression: 'CurrentThread::IsMainThread()'
UnityEngine.JsonUtility:FromJsonInternal(String, Object, Type)
UnityEngine.JsonUtility:FromJsonOverwrite(String, Object)
GraphProcessor.SerializableObject:OnAfterDeserialize() (at Assets\com.alelievr.NodeGraphProcessor\Runtime\Utils\SerrializableObject.cs:54)

[C:\buildslave\unity\build\Runtime/BaseClasses/BaseObject.cpp line 288] 
(Filename: Assets/com.alelievr.NodeGraphProcessor/Runtime/Utils/SerrializableObject.cs Line: 54)

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) UnityEngine.JsonUtility.FromJsonInternal (string,object,System.Type) [0x00009] in <1386288601af43018501cce2912f52f4>:0
  at UnityEngine.JsonUtility.FromJsonOverwrite (string,object) [0x00059] in <1386288601af43018501cce2912f52f4>:0
  at GraphProcessor.SerializableObject.OnAfterDeserialize () [0x00090] in C:\home\Code\NodeGraphProcessor\Assets\com.alelievr.NodeGraphProcessor\Runtime\Utils\SerrializableObject.cs:54
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <437ba245d8404784b9fbab9b439ac908>:0
```

line 54 can be seen here 

```
            else if (typeof(UnityEngine.Object).IsAssignableFrom(type))
            {
                ObjectWrapper obj = new ObjectWrapper();
                JsonUtility.FromJsonOverwrite(serializedValue, obj); // <<<<<<<< LINE 54
                value = obj.value;
            }
```
which is odd as [the documentation for FromJsonOverwrite](https://docs.unity3d.com/ScriptReference/JsonUtility.FromJsonOverwrite.html) makes it look like this this should be safe from threads other than main.

I'll post more if I find it.

### PR DESCRIPTION
**Pull request by alelievr**
:warning: This PR bumps the minimum Unity version to 2020.2, this is mainly because of many serialization issues with the `[SerializeReference]` attribute on previous versions.

This PR should fix #67, #95 and #81

Please refer to the [Upgrade Guide](https://github.com/alelievr/NodeGraphProcessor/blob/6133ba4b74198d99e012d0b6127e7509b080c2b6/UPGRADE-GUIDE.md) for any additional information or issue after upgrading.

Note that due to some troubles with [ApplyModifiedProperties](https://docs.unity3d.com/ScriptReference/SerializedObject.ApplyModifiedProperties.html) and [SerializeReference] We can't really use PropertyFields in the UI regarding nodes or parameters. So it means that there is no support for property drawers like Min, Max, Range, ect.
Because of this, I added a workaround class [ExposedParameterFieldFactory](https://github.com/alelievr/NodeGraphProcessor/blob/6133ba4b74198d99e012d0b6127e7509b080c2b6/Assets/com.alelievr.NodeGraphProcessor/Editor/Views/ExposedParameterFieldFactory.cs) that creates PropertyFields for Exposed Parameters, it requires a bit more code to implement and it's not pretty but at least it allows to have custom property drawers on exposed parameters.

This PR also improves the default behavior of parameters, which now has more settings in the graph (for example the float can be exposed as a range in the UI now, the color has an HDR option as well, etc.):
image

### CODE REVIEW

**Comment by TeorikDeli** [comment]
Wow! That's looking great @alelievr ! I have a report to write until thursday, so I can't test/review much for now. But I will when I finish it, if it is OK to you. Also, I spilled some ice tea on my laptop (🙄) and while it is at the service, I am using the desktop at the office (and I have limited time at the office because of the country's covid-19 restrictions).

By the way, we implemented Waitables (Wait for second, wait for frame). I can also implement it if you want after this.

**Comment by alelievr** [comment]
Thanks :) 

You can take your time, I have some stuff to finish as well and I'm still testing this PR.

> By the way, we implemented Waitables

Sounds great! Doesn't it allow the graph to be executed in several parts? or is it something else?

**Comment by TeorikDeli** [comment]
Yeah, it looks like this https://docs.unrealengine.com/en-US/BlueprintAPI/Ability/Tasks/WaitDelay/index.html . One with a time parameter, one with a frame parameter (and without async task output). I used Monobehaviours for this; but right now I generating a new gameobject for each Wait node, but I will probably change this to "one gameobject multiple Monobehaviours". I am not sure if I can correctly manage "one gameobject one Monobehaviour" right now, but that's my final goal. Of course, this approach won't work outside of the runtime, but [Editor Coroutines](https://docs.unity3d.com/Packages/com.unity.editorcoroutines@1.0/manual/index.html) can be implemented in the future.

**Comment by alelievr** [comment]
@TeorikDeli any ETA you can give for your review? :)

**Comment by TeorikDeli** [comment]
So sorry for the delay, I will start looking today @alelievr .

**Comment by TeorikDeli** [comment]
Well, as I can see/test, Serialization works very well 🤘🏻 My only concerns are object pickers. And I found minor errors related to GraphBehaviour (which is a great idea!).

About object pickers; I think, only the GraphBehaviour inspector and graph window should be allowed to pick scene objects. Because asset files shouldn't try to serialize scene objects (which will eventually cause errors and problems). I already solved this problem with checking graph.name (asset files have name, GraphBehaviours doesn't). I couldn't find any other solution.

And about minor problems; when we add GraphBehaviour components, it automatically breaks the inspector. Because it is probably try to use the graphEditor before the graph is created. Simple null check solved it. And also, BaseGraphWindow tries to unload graph asset even for the GraphBehaviour. Opening another GraphView is triggering this. Graph name check also solves this. And the last one is BaseGraphView's "RegisterCompleteObjectUndo". If I edit the GraphBehaviour graph, then "Discard Changes" for that scene, the graph gives null ref errors. I think the graph view also should reset to scene's saved version. I am not sure how to solve this, so I didn't do anything on this one.

I can commit my changes to this branch, or write as comments to the files. Other than that everything works well. 👌🏻

**Comment by alelievr** [comment]
Nice :) You can push your changes directly in this branch, it's fine.

I totally agree for object pickers begin allowed to pick objects in the scene, in fact without this, GraphBehaviour doesn't make much sense. Checking the name should work indeed, but it's not robust, if someone assigns a name to the graph ScriptableObject, then the UI will break. Maybe a boolean in the graph would be better in this case? Something like "allowSceneObjects"

I'll take care of the nullref in the editor and the graph reload when the scene changes are discarded, I this as you said that `EditorSceneManager.activeSceneChangedInEditMode` will solve the issue, I just need to figure out where to put it.
I'll probably have to do a property in the BaseGraphView class to know if the graph is an asset or not, in which case we don't unload it and link it to the current scene.

Thank you for testing the feature :)

**Comment by TeorikDeli** [comment]
🕺🏻 OK then, I will comment out "allowSceneObjects" parts, then push it. By the way, I think, a boolean in the graph might be good as a temporary solution. Because if in the future when a component like GraphBehaviour for graph assets is added, then we'll have the same problem in its inspector, probably. 🤔 Maybe editing that boolean on-the-go (I mean, while constructing the editor) would be a solution. I don't know, maybe inspector constructor should do this while it is being called (with an argument?). 🤷🏻‍♂️

**Comment by alelievr** [comment]
I didn't think about what happens when you close the scene with the graph editor opened either (I guess the window should close itself), and in this case, we'll need a boolean or maybe more to "link" the graph to a certain scene.

Didn't test Addressables either :/

**Comment by TeorikDeli** [comment]
All is looking very well 👌🏻  And about the Addressables, I think both graph and object as addressables is an extreme situation right now 😅  Other than that, it should work without any problem. We are using graphs as addressables in our project without any problem (of course prefab instantiating is another thing and should not be this project's problem).

**Comment by alelievr** [comment]
Hum, so apparently when you discard the changes in a scene it actually closes it so I can't keep my graph window alive because the scene is closing.

I guess I'd need something else to be able to keep the window alive even after closing the scene, displaying something in the window and when the scene is opened again, re-bind the graph to the window. But it's a lot more work and I don't want to overload this PR.

Other than that I think, we're good :) What do you think?

**Comment by TeorikDeli** [comment]
I think it is ready 🕺🏻

**Comment by alelievr** [comment]
I've edited the min version section in the readme:
image

Let's go! :shipit:

**Pull request merged**
